version: "3.3"
services:
  web:
    image: php:7.4.22-apache
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./public:/var/www/html
      - ./src:/home/src
    container_name: local_web
    env_file: ./.env.php
    ports:
        - 8080:80
  db:
    image: mysql:8.0.26
    volumes:
      - ./mysql:/home
    container_name: local_db
    env_file: ./.env.mysql
